/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFavoriteButton: typeof import('./src/components/favorites/AddFavoriteButton.vue')['default']
    AlertDialog: typeof import('./src/components/modals/AlertDialog.vue')['default']
    ArtistList: typeof import('./src/components/filters/ArtistList.vue')['default']
    ArtistSidebar: typeof import('./src/components/filters/ArtistSidebar.vue')['default']
    ArtistTagsInput: typeof import('./src/components/favorites/ArtistTagsInput.vue')['default']
    CheckIcon: typeof import('./src/components/icons/CheckIcon.vue')['default']
    ConfirmDialog: typeof import('./src/components/modals/ConfirmDialog.vue')['default']
    ExportIcon: typeof import('./src/components/icons/ExportIcon.vue')['default']
    FavoriteCard: typeof import('./src/components/favorites/FavoriteCard.vue')['default']
    FavoriteModal: typeof import('./src/components/modals/FavoriteModal.vue')['default']
    FavoriteSearchBar: typeof import('./src/components/favorites/FavoriteSearchBar.vue')['default']
    FavoritesGrid: typeof import('./src/components/favorites/FavoritesGrid.vue')['default']
    FilterIcon: typeof import('./src/components/icons/FilterIcon.vue')['default']
    HeaderBar: typeof import('./src/components/layout/HeaderBar.vue')['default']
    ImportIcon: typeof import('./src/components/icons/ImportIcon.vue')['default']
    LanguageIcon: typeof import('./src/components/icons/LanguageIcon.vue')['default']
    LoginPage: typeof import('./src/components/auth/LoginPage.vue')['default']
    PlusIcon: typeof import('./src/components/icons/PlusIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    SettingsIcon: typeof import('./src/components/icons/SettingsIcon.vue')['default']
    SortIconNewest: typeof import('./src/components/icons/SortIconNewest.vue')['default']
    SortIconOldest: typeof import('./src/components/icons/SortIconOldest.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  }
}
