/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: '@request.auth.id != "" && @request.body.owner = @request.auth.id',
      deleteRule: '@request.auth.id != "" && owner = @request.auth.id',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: '_pb_users_auth_',
          help: '',
          hidden: false,
          id: 'relation3479234172',
          maxSelect: 0,
          minSelect: 0,
          name: 'owner',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url4101391790',
          name: 'url',
          onlyDomains: null,
          presentable: false,
          required: true,
          system: false,
          type: 'url',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text724990059',
          max: 0,
          min: 0,
          name: 'title',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'json1758691358',
          maxSize: 0,
          name: 'artists',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          help: '',
          hidden: false,
          id: 'select2363381545',
          maxSelect: 0,
          name: 'type',
          presentable: false,
          required: true,
          system: false,
          type: 'select',
          values: ['youtube', 'soundcloud'],
        },
        {
          exceptDomains: null,
          help: '',
          hidden: false,
          id: 'url3277268710',
          name: 'thumbnail',
          onlyDomains: null,
          presentable: false,
          required: false,
          system: false,
          type: 'url',
        },
        {
          help: '',
          hidden: false,
          id: 'json3670672454',
          maxSize: 0,
          name: 'timestamps',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_2151843437',
      indexes: [],
      listRule: '@request.auth.id != "" && owner = @request.auth.id',
      name: 'favorites',
      system: false,
      type: 'base',
      updateRule: '@request.auth.id != "" && owner = @request.auth.id',
      viewRule: '@request.auth.id != "" && owner = @request.auth.id',
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_2151843437')

    return app.delete(collection)
  },
)
