/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule: '@request.auth.id != "" && @request.body.owner = @request.auth.id',
      deleteRule: '@request.auth.id != "" && owner = @request.auth.id',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text1579384326',
          max: 0,
          min: 0,
          name: 'name',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'date2669484962',
          max: '',
          min: '',
          name: 'dateAttended',
          presentable: false,
          required: true,
          system: false,
          type: 'date',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text2213199344',
          max: 0,
          min: 0,
          name: 'venue',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: '_pb_users_auth_',
          help: '',
          hidden: false,
          id: 'relation3479234172',
          maxSelect: 1,
          minSelect: 0,
          name: 'owner',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_1093733721',
      indexes: [
        'CREATE INDEX `idx_events_owner_date_attended` ON `events` (`owner`, `dateAttended`)',
      ],
      listRule: '@request.auth.id != "" && owner = @request.auth.id',
      name: 'events',
      system: false,
      type: 'base',
      updateRule:
        '@request.auth.id != "" && owner = @request.auth.id && (@request.body.owner:isset = false || @request.body.owner = @request.auth.id)',
      viewRule: '@request.auth.id != "" && owner = @request.auth.id',
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_1093733721')

    return app.delete(collection)
  },
)
