/// <reference path="../pb_data/types.d.ts" />
migrate(
  (app) => {
    const collection = new Collection({
      createRule:
        '@request.auth.id != "" && @request.body.owner = @request.auth.id && @collection.events.id ?= @request.body.eventId && @collection.events.owner ?= @request.auth.id && @collection.artists.id ?= @request.body.artistId && @collection.artists.owner ?= @request.auth.id',
      deleteRule: '@request.auth.id != "" && owner = @request.auth.id',
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          help: '',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: true,
          collectionId: 'pbc_1093733721',
          help: '',
          hidden: false,
          id: 'relation1149286663',
          maxSelect: 1,
          minSelect: 0,
          name: 'eventId',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_4185980916',
          help: '',
          hidden: false,
          id: 'relation1841317735',
          maxSelect: 1,
          minSelect: 0,
          name: 'artistId',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          autogeneratePattern: '',
          help: '',
          hidden: false,
          id: 'text3455093269',
          max: 0,
          min: 0,
          name: 'artistName',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          help: '',
          hidden: false,
          id: 'select1170263614',
          maxSelect: 1,
          name: 'verdict',
          presentable: false,
          required: false,
          system: false,
          type: 'select',
          values: ['dislike', 'one-star', 'two-stars', 'three-stars'],
        },
        {
          cascadeDelete: false,
          collectionId: '_pb_users_auth_',
          help: '',
          hidden: false,
          id: 'relation3479234172',
          maxSelect: 1,
          minSelect: 0,
          name: 'owner',
          presentable: false,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          hidden: false,
          id: 'autodate2990389176',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate3332085495',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      id: 'pbc_2758201643',
      indexes: [
        'CREATE INDEX `idx_performances_owner_event` ON `performances` (`owner`, `eventId`)',
        'CREATE INDEX `idx_performances_owner_artist` ON `performances` (`owner`, `artistId`)',
      ],
      listRule: '@request.auth.id != "" && owner = @request.auth.id',
      name: 'performances',
      system: false,
      type: 'base',
      updateRule:
        '@request.auth.id != "" && owner = @request.auth.id && (@request.body.owner:isset = false || @request.body.owner = @request.auth.id) && (@request.body.eventId:isset = false || (@collection.events.id ?= @request.body.eventId && @collection.events.owner ?= @request.auth.id)) && (@request.body.artistId:isset = false || (@collection.artists.id ?= @request.body.artistId && @collection.artists.owner ?= @request.auth.id))',
      viewRule: '@request.auth.id != "" && owner = @request.auth.id',
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('pbc_2758201643')

    return app.delete(collection)
  },
)
